### PR TITLE
Removed action tutorials interfaces dependency

### PR DESCRIPTION
**Pull request by ahcorde**
Related with https://github.com/ros2/demos/issues/702 and https://github.com/ros2/demos/pull/701#issuecomment-2319604673

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
This looks good to me, thanks @ahcorde .  I'll note that this should work fine going all the way back to Humble, so it should be safe to merge in regardless of the branching strategy on this repository.

**Comment by ahcorde** [comment]
@bmagyar do you mind to take a quick look ?

**Review by bmagyar — APPROVED** [review]
Grand! Thank you for the extra note @clalancette

**Comment by ahcorde** [comment]
I can't merge the PR, do you mind to merge it and release it ?

**Comment by bmagyar** [comment]
Give me a minute to fix the CI :)

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/42689

**Pull request merged**
