### PR TITLE
Add mouse_teleop

### PR DESCRIPTION
**Pull request by efernandez**

### CODE REVIEW

**Comment by bmagyar** [comment]
Me gusta!
Although I find it very cool, there is one condition for me to merge this...

The infamous º. This is not a degree sign. Please replace it with the appropriate symbol or with 'deg' or 'degrees'.


Apart from this, a BIG +1, awesome idea!

**Comment by adolfo-rt** [comment]
Style suggestion: It's difficult to see the blue line representing linear velocity against the black background. Consider an alternative color scheme in which the commands stand out more strongly. Making the background lighter could be a simple solution.

Otherwise, great idea

**Comment by efernandez** [comment]
@bmagyar @adolfo-rt Thanks for your suggestions. I've just pushed the fixes for them.

**Comment by bmagyar** [comment]
Nice! Since this now meets all the comments, I'm gonna merge right ahead.

**Pull request merged**
