### PR TITLE
Allow for sending messages *containing* an array

### PR DESCRIPTION
**Pull request by dogoepp**
These changes allow to use the joypad values to fill an array-typed message, like `Float64MultiArray`.

We use this to send commands to move several joints of a robot controlled in velocity mode (with ros_control). Here is a sample of the configuration:

```yaml
teleop:
  arm:
    type: topic
    message_type: std_msgs/Float64MultiArray
    topic_name: /dynamixel_controllers/omni_arm_controller/command
    deadman_buttons: [5]
    axis_mappings:
      -
        axis: 0
        target: data[0]
        scale: 1.0
      -
        axis: 1
        target: data[1]
        scale: 1.0
      -
        axis: 4
        target: data[2]
        scale: 1.0
      -
        axis: 3
        target: data[3]
        scale: 1.0

    message_value:
      -
        target: data[4]
        value: 0
```

### CODE REVIEW

**Comment by bmagyar** [comment]
Thanks!! Do you have an easy way in mind to add a test for this?

**Comment by dogoepp** [comment]
To easily test, one could use the following `test_joy_teleop.launch`

```xml
<?xml version="1.0"?>
<launch>
  <!-- Parameters for the two nodes -->
  <rosparam file="$(find YOUR_PACKAGE)/config/test_joy_teleop.yaml"/>

  <!-- starting the hardware interface and controllers -->
  <node name="joy_node" pkg="joy"
        type="joy_node" output="screen" clear_params="true"
        required="true"/>
  <node name="joy_teleop" pkg="joy_teleop"
        type="joy_teleop.py" output="screen" clear_params="true"
        required="true"/>
</launch>
```

and `test_joy_teleop.yaml`:

```yaml
joy_node:
  dev: /dev/input/js0

teleop:
  arm:
    type: topic
    message_type: std_msgs/Float64MultiArray
    topic_name: /command
    deadman_buttons: [5]
    axis_mappings:
      -
        axis: 0
        target: data[0]
        scale: 1.0
      -
        axis: 1
        target: data[1]
        scale: 1.0
      -
        axis: 4
        target: data[2]
        scale: 1.0
      -
        axis: 3
        target: data[3]
        scale: 1.0

    message_value:
      -
        target: data[4]
        value: 0
```

And putting these in a package. The launch file should be put in a package and `YOUR_PACKAGE` should be replaced with the package name.

With this, you can just display the messages on the `/command` topic. We use it daily with our robot and it works like a charm.

@resibots

**Comment by dogoepp** [comment]
@bmagyar may I ask why this is closed ? Was something amiss ?

**Comment by bmagyar** [comment]
I realized that the `melodic-devel` branch in the end served no purpose but was an outdated version of `kinetic-devel`, even releases were done from there. I removed `melodic-devel` and apparently github was intelligent enough to automagically close the PR-s targeting this branch.

I am however very open to merge this. I think there is definitely value there but I'd hope to see a unit test ensuring that things work as expected (and remain working). Can you provide a `rostest` implementing this?

Could you please retarget this PR or open a new PR against `kinetic-devel`?

**Pull request closed without merging**
